<?php

namespace Container2Pk0I6Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewTaskTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\NewTaskType' shared autowired service.
     *
     * @return \App\Form\NewTaskType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/NewTaskType.php';

        return $container->privates['App\\Form\\NewTaskType'] = new \App\Form\NewTaskType();
    }
}
