<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIRnMqR9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIRnMqR9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIRnMqR9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIRnMqR9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIRnMqR9\App_KernelDevDebugContainer([
    'container.build_hash' => 'IRnMqR9',
    'container.build_id' => 'b751fdb3',
    'container.build_time' => 1676022229,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIRnMqR9');
